# This file should go into ~/.config/anonidgen/config.yaml
#
# You can customize the settings below to your needs by uncomment a line and
# edit it.
#
# The default value will be used if the setting is commented out


#username:
#  chars: 12
#
#email:
#  domain: 'example.com'
#  length: 6
#  prefix: ''
#
#password:
#  chars: 32

username:
  chars: 2

email:
  domain: 'test.com'
  length: 19
  prefix: ''

password:
  chars: 8

