# THIS FILE SHOULD NOT BE CUSTOMIZED!
#
# FOR CUSTOMIZATION COPY THIS FILE INTO '~/.config/anonidgen/config.yaml'
# ALL CUSTOMIZATIONS TO YOUR LOCAL CONFIG WILL OVERWRITE THE VALUES IN HERE.
# IF YOU DON'T OVERWRITE SPECIFIC VALUES, THE DEFAULT WILL BE USED.

username:
  chars: 16

email:
  domain: 'guerrillamail.com'
  chars: 12
  prefix: ''

password:
  chars: 32
